CREATE TABLE servicos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(100)             NOT NULL,
    descricao       VARCHAR(500),
    categoria       VARCHAR(60)              NOT NULL,
    preco           NUMERIC(10, 2)           NOT NULL,
    duracao_minutos INTEGER                  NOT NULL,
    criado_em       TIMESTAMP WITH TIME ZONE NOT NULL,
    atualizado_em   TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_servicos_preco CHECK (preco > 0),
    CONSTRAINT ck_servicos_duracao CHECK (duracao_minutos > 0)
);
